# frozen_string_literal: true

source 'https://cdn.cocoapods.org/'
source 'git@github.com:applicaster/CocoaPods.git'

platform :ios, '11.0'
install! 'cocoapods', share_schemes_for_development_pods: true
project '../../../localProject/apple/FrameworksApp.xcodeproj'

pre_install do |_installer|
  # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end

target 'FrameworksApp' do
  use_frameworks!
  pod 'ZappCore', path: '../../zapp-core/apple/ZappCore.podspec'
  pod 'QuickBrickXray', path: './QuickBrickXray.podspec', testspecs: ['UnitTests']
  # pod 'XrayLogger', git: 'https://github.com/applicaster/x-ray.git', branch: 'master'
  # pod 'Reporter', git: 'https://github.com/applicaster/x-ray.git', branch: 'master'
  # pod 'LoggerInfo', git: 'https://github.com/applicaster/x-ray.git', branch: 'master'
  pod 'XrayLogger', path: '/Users/antonkononenko/Work/x-ray/Xraylogger.podspec'
  pod 'Reporter', path: '/Users/antonkononenko/Work/x-ray/Reporter.podspec'
  pod 'LoggerInfo', path: '/Users/antonkononenko/Work/x-ray/LoggerInfo.podspec'
  target 'FrameworksAppTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
    end
  end
end
