export const EVENTS = {
  playerCreated: "Player Created",
  mediaLoad: "Media Entry Load",
  adBreakStarted: "Ad Break Started",
  adBegin: "Ad Begin",
  adEnd: "Ad End",
  adError: "Ad Error",
  adBreakEnd: "Ad Break End",
  playerLoadedVideo: "Player Loaded Video",
  playerPlaying: "Player Playing",
  playerResumed: "Player Resumed",
  playerPaused: "Player Paused",
  playerSeek: "Player Seek",
  playerSeekEnd: "Player Seek End",
  playerEnded: "Player Ended",
  playerBuffering: "Player Buffering",
  playerClosed: "Player Closed",
};
